### ISSUE TITLE
Store gateway pods heartbeating stale IP addresses

### ISSUE THREAD

**Issue by amckinley** [cortexproject/cortex#2950] opened 2020-07-29 16:10 UTC
Yesterday during an upgrade, we cycled out our 3 `store-gateway` pods in kubernetes, after which almost all queries against cortex started failing with a "tcp timeout: no route to host 10.x.x.x". Upon investigation, we discovered the `store-gateway` ring showed two out of three hosts reporting the incorrect IP address, even though they were still heartbeating on a regular basis. Below is a screenshot of the storage ring status, as well as a screenshot of the actual Kubernetes-assigned IP addresses of the `store-gateway` pods. I manually hit the "forget" button on the two stale IP addresses, and the correct IPs were immediately populated at the next heartbeat interval. We're running cortex v1.2.0, and can provide our config on request.

![Screen Shot 2020-07-29 at 8 49 45 AM](https://user-images.githubusercontent.com/54160/88824179-dc45d200-d17a-11ea-9426-586da6bd7cfa.png)

![Screen Shot 2020-07-29 at 8 49 50 AM](https://user-images.githubusercontent.com/54160/88824365-1911c900-d17b-11ea-9eec-da938c3d48e0.png)

**Comment by amckinley** [comment] 2020-07-29 16:55
For what it's worth, attempting to repro by deleting one of the `store-gateway` pods just now didn't work.

**Comment by pracucci** [comment] 2020-07-30 09:57
> ring showed two out of three hosts reporting the incorrect IP address

Where the incorrect IP addresses the one of the previous store-gateways with the same ID? For example, was `10.20.53.16` the IP address of the `store-gateway-0` before the rollout?

**Comment by pracucci** [comment] 2020-07-30 10:18
I've fixed an issue in #2954. I'm not sure it's the root cause of **your** issue, because the conditions to trigger it should be difficult to reproduce in a real scenario (because I would expect the previous instance having the `ACTIVE` state while the new one has the `JOINING` state and in this case the bug fixed in #2954 doesn't trigger).

_Let's continue the investigation here. Could you check out my previous question, please?_

**Closed** 2020-07-30 10:58 UTC
Labels: storage/blocks

**Comment by amckinley** [comment] 2020-07-30 15:27
> > ring showed two out of three hosts reporting the incorrect IP address
> 
> Were the incorrect IP addresses the one of the previous store-gateways with the same ID? For example, was `10.20.53.16` the IP address of the `store-gateway-0` before the rollout?

That's my assumption, but I have no way of knowing for sure.

**Comment by pracucci** [comment] 2020-07-30 15:36
Would you be able to try if #2954 fixes your issue? _If not, please reopen this issue._

**Comment by amckinley** [comment] 2020-07-30 17:35
Well, I don't have an easy repro, so it would be hard to tell. After #2954 promotes to (presumably) v1.3.0, I'll update our cluster and if I see this issue again I'll reopen.
