### ISSUE TITLE
Idea: Content-Addressable series data chunks

### ISSUE THREAD

**Issue by leth** [cortexproject/cortex#1034] opened 2018-09-27 10:37 UTC
We might be able to make significant storage gains for series which are a) scraped together b) have the same value and c) never change (or change in sync) if series data was stored in a content-addressable manner.

Since this would be a pretty fundamental change it would need some good analysis to confirm that the saving we would actually gain are worth the effort involved.

We'd have to omit things like the metric name and the start time (store them elsewhere), and work in offsets.

We could also omit the OrgID from the chunk, but this might make accounting or cleanup prohibitively expensive.

**Comment by bboreham** [comment] 2018-09-27 11:06
First guess is the main candidate is chunks which are all zeros.  Of which there are a surprising number, sometimes caused by bugs in cAdvisor.  See also #631 

Sadly the majority of storage effort goes into the index, which will rarely be common across instances.

**Comment by leth** [comment] 2018-10-08 10:43
Another candidate: chunks which are all 1s - kube-state-metrics publishes a lot of those!

**Comment by gouthamve** [comment] 2019-11-11 17:10
I can't see how this is feasible and there has been no movement on this for over a year. I'm going to close this but please feel free to re-open it if you'd like.

**Closed by gouthamve** 2019-11-11 17:10 UTC
