### ISSUE TITLE
Ingester not leaving Ring From Distributor Rings And getting "expanding series: too many unhealthy instances in the ring"

### ISSUE THREAD

**Issue by Rahuly360** [cortexproject/cortex#4476] opened 2021-09-14 07:33 UTC
ingester pod is not getting up and getting the logs 
level=warn ts=2021-09-14T07:30:48.315025417Z caller=lifecycler.go:237 msg="found an existing instance(s) with a problem in the ring, this instance cannot become ready until this problem is resolved. The /ring http endpoint on the distributor (or single binary) provides visibility into the ring." ring=ingester err="instance obf-cortex-ingester-b66f96644-wxpvr past heartbeat timeout
To start Ingester we have to manually forget the Ingester ring from Distributor. Is there any property to remove unhealthy rings automatically  from Distributor in Cortex

**Comment by doit05** [comment] 2021-09-24 07:55
curl -X POST 'http://host:3100/ring' -d 'forget= obf-cortex-ingester-b66f96644-wxpvr '

**Comment by apmartins85** [comment] 2021-09-25 19:55
Hi Folks.
This is something really strange to me ..I'm not sure if I'm doing a mistake in my config or it is the behaviour expected but sound is weird, think that you have to manually kick out an unhealthy instance (via command line or ui).

**Comment by bboreham** [comment] 2021-10-01 15:45
Seems like a duplicate of #1521.
Yes this is expected, although not ideal.

**Closed by bboreham** 2021-10-01 15:45 UTC
