### ISSUE TITLE
Query all tenants 

### ISSUE THREAD

**Issue by papovyr** [cortexproject/cortex#2261] opened 2020-03-12 02:23 UTC
Hi,
I have multiple projects and they have their own tenants
So each team can see all their own metrics 
But as operations team we need to be able to query all tenants and build overview dashboard

Is there a specific value that i can set for X-Scope-OrgID to query all tenants or any advices on this ?

**Comment by jtlisi** [comment] 2020-03-12 03:15
There is currently no way to do this.

**Comment by csmarchbanks** [comment] 2020-03-12 13:51
There is an open issue for this (https://github.com/cortexproject/cortex/issues/923), but someone will have to do the actual work.

Closing this as a duplicate of the linked issue.

**Closed by csmarchbanks** 2020-03-12 13:51 UTC
