### ISSUE TITLE
Block corruption after sporadic S3 failures

### ISSUE THREAD

**Issue by amckinley** [cortexproject/cortex#3418] opened 2020-10-28 19:00 UTC
**Describe the bug**
Using cortex v1.3.0 deployed on K8S, we had an unrelated infrastructure issue that caused a subset of reads and writes from Cortex pods to S3 to fail. This resulted in two different symptoms:

1. all queries for blocks not currently available on the ingesters would fail either with a timeout, or with this error: `rpc error: code = Aborted desc = fetch series for block 01ENH6QJ94B12XSNQ3WNMST105: add chunk preload: reference sequence 1 out of range`
1. the compactor pods stopped making progress, logging this failure over and over:
```
level=info ts=2020-10-27T03:25:14.284010158Z caller=compact.go:949 component=compactor org_id=fake msg="start of GC"
level=info ts=2020-10-27T03:25:14.347945408Z caller=compact.go:961 component=compactor org_id=fake msg="start of compactions"
level=info ts=2020-10-27T03:26:12.948356642Z caller=compact.go:694 component=compactor org_id=fake group="0@{__org_id__=\"fake\"}" groupKey=0@5679675083797525161 msg="compaction available and planned; downloading blocks" plan="[/data/compact/0@5679675083797525161/01EHXV9J7M40RFJGBWG2NNH0CW /data/compact/0@5679675083797525161/01EHXVKH3RXHARRQHK10HXHENJ /data/compact/0@5679675083797525161/01EHXVK7FZTWPJDKGWS9VDAB35 /data/compact/0@5679675083797525161/01EHXVJ4STKDTSX0PNRJ8YDCRS /data/compact/0@5679675083797525161/01EHXVJBRE37SQ84DZ2Z3SRDCM /data/compact/0@5679675083797525161/01EHXVKHQ21D6WCX4J4HNGFHPW /data/compact/0@5679675083797525161/01EHXVJ8GVM2121X3C74BD3A80 /data/compact/0@5679675083797525161/01EHXVJSRTK2AP2B60BERGKAJZ /data/compact/0@5679675083797525161/01EHXVJAZMGFYWSA0FWPMGTFW7 /data/compact/0@5679675083797525161/01EHXVJQCTDYH0XB1DSKMY5Q91 /data/compact/0@5679675083797525161/01EHXVK434TSQ00YD4FM3CJZ1B /data/compact/0@5679675083797525161/01EHXVK7SBYG37G07XP6KW6E85 /data/compact/0@5679675083797525161/01EHXVJDMG0ZM3GDTPR56PBF9V /data/compact/0@5679675083797525161/01EHXVKRRNEZY78623M3DPB2VG /data/compact/0@5679675083797525161/01EHXVKMQRTW20XA5T82VWYGM2 /data/compact/0@5679675083797525161/01EHXVKV12MW5JDA4V2HS80B7K /data/compact/0@5679675083797525161/01EHXVJN7WVAG3QJRW5020XWSG /data/compact/0@5679675083797525161/01EHXVKYDANVA2W5TQW1NX7DK9 /data/compact/0@5679675083797525161/01EHXVKQRA2QMZF8YPMHWY1YBB /data/compact/0@5679675083797525161/01EHXVM3PWX25C7S6WBC16EKJ1 /data/compact/0@5679675083797525161/01EHXVP4K5V9D1Y5REKXQQ74SN]"
level=info ts=2020-10-27T03:34:13.467588747Z caller=blocks_cleaner.go:101 component=cleaner msg="started hard deletion of blocks marked for deletion"
level=error ts=2020-10-27T03:37:29.06848172Z caller=compactor.go:339 component=compactor msg="failed to compact user blocks" user=fake err="compaction: group 0@5679675083797525161: block with not healthy index found /data/compact/0@5679675083797525161/01EHXVJ4STKDTSX0PNRJ8YDCRS; Compaction level 1; Labels: map[__org_id__:fake]: 1/1637953 series have an average of 1.000 out-of-order chunks: 0.000 of these are exact duplicates (in terms of data and time range)"
level=info ts=2020-10-27T03:42:42.004841022Z caller=fetcher.go:453 component=cleaner org_id=fake component=block.BaseFetcher msg="successfully synchronized block metadata" duration=8m28.497361842s cached=41041 returned=41041 partial=0
```

I resolved this by deleting the two "bad" blocks manually from S3: `01EHXVJ4STKDTSX0PNRJ8YDCRS` and `01ENH6QJ94B12XSNQ3WNMST105`. (I saved copies of these blocks if they would be helpful for debugging). After deleting the bad blocks and restarting the compactor and store-gateway pods, things seemed to recover and queries for historical data started working again.

If the response to this issue is "yeah, you're gonna get data corruption if your S3 writes start failing randomly", I can understand that, but I definitely think it's a bug that a single corrupted block can totally break the compactors and queriers. If this ever happens again outside of business hours, a human would have to get paged and intervene to bring metrics back online. 

**To Reproduce**
I'm not sure how reproducible this issue is, outside of running S3 calls through `toxiproxy` or similar to fail a subset of calls.

**Expected behavior**
Lots of log spew about a corrupted block, but not a failure of all queries attempting to read from the bad block.

**Environment:**
Cortex v1.3.0, running in microservices mode, with K8S manifests generated by `cortex-jsonnet`. Manifests and jsonnet config available on request.

**Storage Engine**
- [X] Blocks
- [ ] Chunks

**Comment by amckinley** [comment] 2020-10-28 21:27
Update: I've now found a third corrupted block that breaks every query that hits it. I'm starting to get extremely worried that I need to scan all of our block files to prevent queries from breaking at random.

**Comment by amckinley** [comment] 2020-10-28 22:45
Update: there are at least a dozen such blocks. I'm trying to find a way to programmatically scan our S3 bucket for these blocks, because right now I can only find them by running queries that go back as many days as possible.

**Comment by pracucci** [comment] 2020-10-29 09:45
Thanks @amckinley for your report. I'm going to try to make some hypothesis, but would need your help to validate them.

> Using cortex v1.3.0

As a general rule, I would suggest to always run the latest Cortex version (1.4.0 as of today). In particular, the blocks storage is still subject of heavy development and, in every release, we fix a lot of bugs, either in Cortex, Thanos or Prometheus TSDB.

> all queries for blocks not currently available on the ingesters would fail either with a timeout, or with this error: `rpc error: code = Aborted desc = fetch series for block 01ENH6QJ94B12XSNQ3WNMST105: add chunk preload: reference sequence 1 out of range`

The error `reference sequence 1 out of range` may be caused by a block missing files in its `chunks/` directory. Given you mentioned you kept a copy of such corrupted blocks, could you show me the content of `meta.json` and the list of files inside the `chunks/` directory of the block `01ENH6QJ94B12XSNQ3WNMST105`?

> all queries for blocks not currently available on the ingesters would fail either with a timeout

Not all queries should fail because of a corrupted block. Only queries hitting a time range overlapping with the corrupted block's time range are expected to fail. The "timeout" looks an unrelated issue to me, while you should the error `reference sequence 1 out of range` only when running a query whose time range overlaps a corrupted block.

> the compactor pods stopped making progress, logging this failure over and over:
> [...]
> I definitely think it's a bug that a single corrupted block can totally break the compactors and queriers

Shouldn't break queriers, but 💯  agree on compactor. It's a known issue #2866 and something we want to work on soon.

**Comment by amckinley** [comment] 2020-11-05 19:22
Sorry; have been on PTO. Answers below:

> As a general rule, I would suggest to always run the latest Cortex version (1.4.0 as of today).

Yep, we're definitely planning on upgrading to 1.4 (just waiting for election-related deploy freeze to end).

> ...could you show me the content of meta.json and the list of files inside the chunks/ directory of the block 01ENH6QJ94B12XSNQ3WNMST105?
```
$ ls chunks/
total 2852352
-rw-r--r--  1 austin.mckinley  staff   512M Oct 25 18:01 000001
-rw-r--r--  1 austin.mckinley  staff   512M Oct 25 18:01 000002
-rw-r--r--  1 austin.mckinley  staff   356M Oct 25 18:01 000003
$ cat meta.json
{
	"ulid": "01ENH6QJ94B12XSNQ3WNMST105",
	"minTime": 1603663200000,
	"maxTime": 1603670400000,
	"stats": {
		"numSamples": 571510700,
		"numSeries": 1349564,
		"numChunks": 4788138
	},
	"compaction": {
		"level": 1,
		"sources": [
			"01ENH6QJ94B12XSNQ3WNMST105"
		]
	},
	"version": 1,
	"thanos": {
		"labels": {
			"__ingester_id__": "ingester-51",
			"__org_id__": "fake"
		},
		"downsample": {
			"resolution": 0
		},
		"source": "receive"
	}
}
```

> Only queries hitting a time range overlapping with the corrupted block's time range are expected to fail.

Right, that's what I meant. I think a better behavior might be for queries to return the results that could be found from uncorrupted blocks, and then log very aggressively about the presence of a corrupted block in the backing store. The alternative is that lots of dashboards will fail to load until a human can manually find and delete the corrupted block(s), which isn't great for the availability of critical infrastructure like metrics. 

Please let me know if you need any more debugging info. I saved ~15 "bad" blocks while I was troubleshooting this earlier.

And finally, one thing I'd really like to see is a tool for scanning our persistent storage for any other blocks in this state. I found [this](https://github.com/thanos-io/thanos/issues/1179) discussion which leads me to hope I can use `thanos bucket inspect` to investigate this (which probably means I'll have to download all our blocks off of S3 to check them, but there are worse things in life).

**Comment by amckinley** [comment] 2020-12-07 18:57
> Not all queries should fail because of a corrupted block. Only queries hitting a time range overlapping with the corrupted block's time range are expected to fail.

This behavior is still really undesirable. We've been slowly triaging our S3 bucket for weeks now, because every time someone finds one of these bad blocks, the only remediation is "a human finds the block and removes it from S3". Why is the behavior "fail the entire query" instead of "noisily log the error and return a subset of the requested data"?

Barring that, we could really use a script or some tooling to assist in the automated detection of these blocks so can clean them all up at once.

**Comment by jpdstan** [comment] 2020-12-09 19:15
I have a suspicion that there might be some unexpected behavior in the S3 client, rather than this necessarily being an issue with the blocks themselves.

[This is the top-level error](https://github.com/thanos-io/thanos/blob/d616214477bfafae38c76668e2f005591bb0b007/pkg/store/bucket.go#L2214-L2214
) that's getting returned. For each problematic block and each of their numerous error messages, we get various `seq` numbers. We've seen `seq` from 0 to ~5 or so. I think the upper bound of ~5 makes sense since these problematic blocks seem to all have ~5 chunks. 

What's interesting though is when `seq == 0`, which would suggest that `len(r.preloads) == 0` in the surrounding `if` block. That seems fishy to me -- the length of that array should be [equal to the number of chunks in that block](https://github.com/thanos-io/thanos/blob/d616214477bfafae38c76668e2f005591bb0b007/pkg/store/bucket.go#L2202-L2202). That led me to look into [how `block.chunkObjs` gets populated](https://github.com/thanos-io/thanos/blob/d616214477bfafae38c76668e2f005591bb0b007/pkg/store/bucket.go#L1424-L1440). Looking into those two `if` blocks, I believe we're branching into the second `if` block, as I don't see `thanos.segment_files` in our `meta.json`. if so, we're calling `bkt.Iter` to grab the chunk filenames directly. This is where I suspect that there's something unexpected happening, and that perhaps we're short-circuiting somewhere or not querying the chunks correctly via the S3 client.

Another observation is that all the problematic blocks i've inspected so far have a compaction level of `1` (which suggests they have _not_ been compacted yet, right?), i.e. they all look like:
```
{
	"ulid": "<block_id_x>",
        ...
	"compaction": {
		"level": 1,
		"sources": [
			"<block_id_x>"
		]
	},
        ...
}
```

**Comment by pstibrany** [comment] 2020-12-10 15:35
> What's interesting though is when `seq == 0`, which would suggest that `len(r.preloads) == 0` in the surrounding `if` block. That seems fishy to me -- the length of that array should be [equal to the number of chunks in that block](https://github.com/thanos-io/thanos/blob/d616214477bfafae38c76668e2f005591bb0b007/pkg/store/bucket.go#L2202-L2202). That led me to look into [how `block.chunkObjs` gets populated](https://github.com/thanos-io/thanos/blob/d616214477bfafae38c76668e2f005591bb0b007/pkg/store/bucket.go#L1424-L1440). Looking into those two `if` blocks, I believe we're branching into the second `if` block, as I don't see `thanos.segment_files` in our `meta.json`. if so, we're calling `bkt.Iter` to grab the chunk filenames directly. This is where I suspect that there's something unexpected happening, and that perhaps we're short-circuiting somewhere or not querying the chunks correctly via the S3 client.

Can you verify that those segment files (= inside "chunks" directory) are stored on S3? Are you using real S3 or some S3-compatible storage?

> Another observation is that all the problematic blocks i've inspected so far have a compaction level of `1` (which suggests they have _not_ been compacted yet, right?), i.e. they all look like:

Yes, these are not compacted.

**Comment by amckinley** [comment] 2020-12-10 18:28
> Can you verify that those segment files (= inside "chunks" directory) are stored on S3? Are you using real S3 or some S3-compatible storage?

Yes, we're using real S3 for all our block storage. We don't use the chunks storage at all.

**Comment by pstibrany** [comment] 2020-12-11 07:46
> Yes, we're using real S3 for all our block storage. We don't use the chunks storage at all.

If the segment files are there (inside "chunks dir), and there is no "segment_files" field in meta.json that would indeed point to some problem with listing them.

**Comment by pracucci** [comment] 2020-12-11 13:51
> If the segment files are there (inside "chunks dir), and there is no "segment_files" field in meta.json that would indeed point to some problem with listing them.

The issue mention "Cortex v1.3.0". If that's still the case, then we didn't write "segment_files" in the `meta.json` at that time. In any case, I would strongly recommend to run Cortex latest (`1.6.0-rc.0` as of today) and see if the issue is still happening. A bunch of fixes has been done in the meanwhile and it's difficult to understand if the reported issue still exist or not.

**Comment by pstibrany** [comment] 2020-12-11 13:56
> > If the segment files are there (inside "chunks dir), and there is no "segment_files" field in meta.json that would indeed point to some problem with listing them.
> 
> The issue mention "Cortex v1.3.0". If that's still the case, then we didn't write "segment_files" in the `meta.json` at that time.

Sorry, I wasn’t clear... I meant that getting this error would indicate issue with listing segment files from S3, if they are present in the bucket.

Agree about upgrade.

**Comment by jpdstan** [comment] 2020-12-18 02:33
So far we haven't seen this issue with blocks created since our upgrade from 1.3.0. This is probably safe to close unless we find otherwise.

**Comment by pracucci** [comment] 2020-12-18 07:45
@jpdstan Ok, thanks for the update. I'm closing it, however feel free to comment / reopen is the issue will happen again.

**Closed by pracucci** 2020-12-18 07:45 UTC
Labels: storage/blocks

**Comment by pstibrany** [comment] 2020-12-18 08:52
Note that we have recently identified one possible source of corrupted blocks when using S3, fix is currently pending in Thanos (https://github.com/thanos-io/thanos/pull/3626).
