### ISSUE TITLE
Memory allocations in batch.newMergeIterator

### ISSUE THREAD

**Issue by cyriltovena** [cortexproject/cortex#2046] opened 2020-01-28 20:33 UTC
I was on-call today and some queries (very high cardinality) causes allocations and therefore GC rate to go crazy, we're running ab3e8360fe30150a516448e4c3bae596dc4d8a17

here is the snapshot of traces alloc space:

![image](https://user-images.githubusercontent.com/1053421/73302266-54d6d080-41e2-11ea-924a-3e5bc8c9f2d6.png)

And a drilldown on the code

![image](https://user-images.githubusercontent.com/1053421/73302182-2eb13080-41e2-11ea-83cc-49d254f94beb.png)

see gc over time the first peak was a new deployment,

![image](https://user-images.githubusercontent.com/1053421/73302324-7041db80-41e2-11ea-9666-130a0aea5f12.png)

I don't think something has been introduced recently but we should at least try to reuse memory in that function. For high cardinality it would help a lot.

**Comment by bboreham** [comment] 2020-01-28 23:09
Duplicate of #1195 ?

**Comment by cyriltovena** [comment] 2020-01-29 13:13
Very much related yes ! Feel free to close.

**Closed** 2020-01-29 15:44 UTC
