### ISSUE TITLE
SIGSEGV in ingesters after enabling `ingester_stream_chunks_when_using_blocks`

### ISSUE THREAD

**Issue by harry671003** [cortexproject/cortex#3994] opened 2021-03-22 18:32 UTC
**Describe the bug**
After enabling `ingester_stream_chunks_when_using_blocks` which was introduced as part of https://github.com/cortexproject/cortex/pull/3889, I've noticed that some ingesters are crashing occasionally with segmentation violation.

**Environment:**
 - Infrastructure: AWS EKS
 - Deployment tool: helm

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**
```
unexpected fault address 0x7fd1e58bf03b
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fd1e58bf03b pc=0x4694b5]

goroutine 2398102 [running]:
runtime.throw(0x260bc28, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc013bbfc20 sp=0xc013bbfbf0 pc=0x435072
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:702 +0x3cc fp=0xc013bbfc50 sp=0xc013bbfc20 pc=0x44be1c
runtime.memmove(0xc0168c80d4, 0x7fd1e58bef19, 0x1a2)
	/usr/local/go/src/runtime/memmove_amd64.s:332 +0x3c5 fp=0xc013bbfc58 sp=0xc013bbfc50 pc=0x4694b5
github.com/cortexproject/cortex/pkg/ingester/client.(*Chunk).MarshalToSizedBuffer(0xc0099d7460, 0xc0168c0000, 0x8276, 0xf9875, 0x1dd, 0x8277, 0x0)
	/__w/cortex-dev/cortex-dev/pkg/ingester/client/ingester.pb.go:3532 +0x1ee fp=0xc013bbfca0 sp=0xc013bbfc58 pc=0x16826ae
github.com/cortexproject/cortex/pkg/ingester/client.(*TimeSeriesChunk).MarshalToSizedBuffer(0xc006cd0800, 0xc0168c0000, 0x8fe9, 0xf9875, 0x8632, 0x8fea, 0x0)
	/__w/cortex-dev/cortex-dev/pkg/ingester/client/ingester.pb.go:3468 +0xd3 fp=0xc013bbfd18 sp=0xc013bbfca0 pc=0x1681e93
github.com/cortexproject/cortex/pkg/ingester/client.(*QueryStreamResponse).MarshalToSizedBuffer(0xc00ac63a40, 0xc0168c0000, 0xf9875, 0xf9875, 0x40a973, 0x2266f60, 0x252e340)
	/__w/cortex-dev/cortex-dev/pkg/ingester/client/ingester.pb.go:2990 +0x1e0 fp=0xc013bbfd80 sp=0xc013bbfd18 pc=0x167f4a0
github.com/cortexproject/cortex/pkg/ingester/client.(*QueryStreamResponse).Marshal(0xc00ac63a40, 0x252e340, 0xc00ac63a40, 0x7fd2a3584850, 0xc00ac63a40, 0x7fd2ca48c201)
	/__w/cortex-dev/cortex-dev/pkg/ingester/client/ingester.pb.go:2956 +0x7a fp=0xc013bbfdd8 sp=0xc013bbfd80 pc=0x167f19a

...

```

See complete log: [ingester-segfault.txt](https://github.com/cortexproject/cortex/files/6184548/ingester-segfault.txt)

**Comment by pstibrany** [comment] 2021-03-23 07:33
Most likely the same problem as https://github.com/cortexproject/cortex/issues/3907

**Comment by pracucci** [comment] 2021-04-01 11:37
I confirm it's a duplicate of #3907. Let's move the discussion there.

**Closed by pracucci** 2021-04-01 11:37 UTC
Labels: component/ingester, type/bug
