### ISSUE TITLE
Trying to pull the images 

### ISSUE THREAD

**Issue by gunjan-DP** [cortexproject/cortex#1741] opened 2019-10-18 10:36 UTC
Getting an error while pulling an image from " image: quay.io/cortexproject/cortex " in Kubernetes. I am using the same k8s to launch the pods and deployment.

**Comment by bboreham** [comment] 2019-10-18 13:03
See https://github.com/cortexproject/cortex/pull/1674#issuecomment-532584306

**Comment by gouthamve** [comment] 2019-12-03 11:33
Dupe of https://github.com/cortexproject/cortex/issues/1805

**Closed by gouthamve** 2019-12-03 11:33 UTC
