### ISSUE TITLE
Query Frontend caches 4xx as successes

### ISSUE THREAD

**Issue by gouthamve** [cortexproject/cortex#1387] opened 2019-05-13 18:00 UTC
We were noticing gaps in our query results and the issue was these responses were being cached by the frontend. After a lot of debugging, the issue turned out that we were storing `4xx` response codes as successes.

In `RoundTripGRPC`: https://github.com/cortexproject/cortex/blob/master/pkg/querier/frontend/frontend.go#L202 we send the request and get the response back.

https://github.com/cortexproject/cortex/blob/master/pkg/querier/frontend/frontend.go#L229-L249
In this we return a `response, nil` for 4xx errors for example. 

That implies we don't even error in `Roundtrip()`: https://github.com/cortexproject/cortex/blob/master/pkg/querier/frontend/frontend.go#L167-L190

In `handleMiss` we persist those extents that are `4xx` in nature: https://github.com/cortexproject/cortex/blob/master/pkg/querier/frontend/results_cache.go#L87-L101

Now next time in `handleHit` when we `mergeAPIResponses`: https://github.com/cortexproject/cortex/blob/335100c25b7cbc54bf44fe9c548a80d8f59e8cec/pkg/querier/frontend/query_range.go#L251-L268 we just set the status as success.

I've traced down the `4xx` responses to be `422` response codes that were being caused by https://github.com/cortexproject/cortex/issues/1354 with that gone, the chances of this occurring should be low but we should handle the `4xx` cases properly.

**Comment by bboreham** [comment] 2019-05-13 20:18
This is broadly the same issue as the `Query failed after 5 retries.` you get when you do something wrong - it shouldn't retry a 4xx.

(#1209 mentions this message but the cause is not described there)

**Comment by gouthamve** [comment] 2019-05-14 14:39
Actually, after some more digging, it turned out to be wrong. We end up returning `4xx` as errors here: https://github.com/cortexproject/cortex/blob/master/pkg/querier/frontend/query_range.go#L143-L146

Which is called by https://github.com/cortexproject/cortex/blob/master/pkg/querier/frontend/roundtrip.go#L137

**Comment by tomwilkie** [comment] 2019-05-17 16:58
I guess we can close this?

**Closed by tomwilkie** 2019-05-17 16:58 UTC
