### ISSUE TITLE
Ingester segfault when querying chunks while head chunks a truncated

### ISSUE THREAD

**Issue by bboreham** [cortexproject/cortex#3907] opened 2021-03-04 11:29 UTC
**Describe the bug**
Crashed inside TSDB while handling a query.

**To Reproduce**
Unknown; only happened once so far.

**Expected behavior**
No crash

**Environment:**
 - Version: `cortexproject/cortex:master-813e156`
 - Infrastructure: Kubernetes
 - Deployment tool: finely-crafted yaml

**Storage Engine**
- [x] Blocks
- [ ] Chunks

**Additional Context**
Logs from the time of the crash, given by Docker as 11:06:20.624 i.e. 180ms after the previous log line:

```
level=info ts=2021-03-04T11:06:19.396885209Z caller=head.go:824 org_id=15437 msg="Head GC completed" duration=1.111514055s
level=info ts=2021-03-04T11:06:19.475381572Z caller=checkpoint.go:95 org_id=15437 msg="Creating checkpoint" from_segment=1425 to_segment=1430 mint=1614852000000
level=warn ts=2021-03-04T11:06:19.523727929Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=1.233714ms err="rpc error: code = Code(429) desc = user=12698: per-metric series limit (local limit: 200000 global limit: 0 actual local limit: 200000) exceeded for series {__name__=\"http_requests_duration_per_route_seconds_sum\", ...
level=warn ts=2021-03-04T11:06:19.616767213Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=1.02415ms err="rpc error: code = Code(400) desc = user=18482: err: duplicate sample for timestamp. timestamp=2021-03-04T11:06:17.35Z, series={__name__=\"envoy_http_downstream_rq_time_bucket\", ...
...
level=warn ts=2021-03-04T11:06:20.417735625Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=1.49353ms err="rpc error: code = Code(400) desc = user=18482: err: duplicate sample for timestamp. timestamp=2021-03-04T11:06:18.261Z, series={__name__=\"envoy_http_downstream_rq_time_bucket\", _weave_service=\"ambassador\", envoy_http_conn_manager_prefix=\"ingress_http\", instance=\"10.0.9.95:8877\", job=\"kubernetes-pods\", kubernetes_namespace=\"ambassador\", kubernetes_pod_name=\"ambassador-5d74845bc7-lln4r\", le=\"0.5\"}" msg="gRPC\n"
level=warn ts=2021-03-04T11:06:20.439362177Z caller=grpc_logging.go:38 method=/cortex.Ingester/Push duration=2.512259ms err="rpc error: code = Code(429) desc = user=12698: per-metric series limit (local limit: 200000 global limit: 0 actual local limit: 200000) exceeded for series {__name__=\"http_requests_duration_per_route_seconds_sum\", ...
unexpected fault address 0x7f68e6d1710a
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f68e6d1710a pc=0x93f9e5]

goroutine 931450810 [running]:
runtime.throw(0x255287c, 0x5)
	/usr/local/go/src/runtime/panic.go:1116 +0x72 fp=0xc07925af70 sp=0xc07925af40 pc=0x434de2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:702 +0x3cc fp=0xc07925afa0 sp=0xc07925af70 pc=0x44bb8c
encoding/binary.bigEndian.Uint64(...)
	/usr/local/go/src/encoding/binary/binary.go:127
github.com/prometheus/prometheus/tsdb/chunkenc.(*bstreamReader).loadNextBuffer(0xc316597f10, 0xc07925b001, 0x4b7b65)
	/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/bstream.go:215 +0xd5 fp=0xc07925afc0 sp=0xc07925afa0 pc=0x93f9e5
github.com/prometheus/prometheus/tsdb/chunkenc.(*bstreamReader).readBit(0xc316597f10, 0x0, 0x18, 0x7)
	/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/bstream.go:129 +0x91 fp=0xc07925afe8 sp=0xc07925afc0 pc=0x93f6a1
github.com/prometheus/prometheus/tsdb/chunkenc.(*xorIterator).readValue(0xc316597f10, 0xc316597f10)
	/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/xor.go:391 +0x39c fp=0xc07925b020 sp=0xc07925afe8 pc=0x941bcc
github.com/prometheus/prometheus/tsdb/chunkenc.(*xorIterator).Next(0xc316597f10, 0x9d1974)
	/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/tsdb/chunkenc/xor.go:324 +0x390 fp=0xc07925b070 sp=0xc07925b020 pc=0x941710
github.com/prometheus/prometheus/tsdb.(*populateWithDelSeriesIterator).Next(0xc613355480, 0x177fc403a8a)
	/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/tsdb/querier.go:566 +0x12d fp=0xc07925b0a8 sp=0xc07925b070 pc=0x9d183d
github.com/prometheus/prometheus/storage.(*chainSampleIterator).Next(0xc40a8fc730, 0x177fc403a8a)
	/__w/cortex/cortex/vendor/github.com/prometheus/prometheus/storage/merge.go:500 +0x5b fp=0xc07925b118 sp=0xc07925b0a8 pc=0x9539ab
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).v2Query(0xc00095a000, 0x2bd8080, 0xc0cc643650, 0xc0cc643560, 0x0, 0x0, 0x0)
	/__w/cortex/cortex/pkg/ingester/ingester_v2.go:908 +0x2af fp=0xc07925b258 sp=0xc07925b118 pc=0x1e79dbf
github.com/cortexproject/cortex/pkg/ingester.(*Ingester).Query(0xc00095a000, 0x2bd8080, 0xc0cc643650, 0xc0cc643560, 0xc00095a000, 0x2189b20, 0x3fe6bd0)
	/__w/cortex/cortex/pkg/ingester/ingester.go:701 +0x55c fp=0xc07925b368 sp=0xc07925b258 pc=0x1e708dc
github.com/cortexproject/cortex/pkg/ingester/client._Ingester_Query_Handler.func1(0x2bd8080, 0xc0cc643650, 0x2488360, 0xc0cc643560, 0x2450420, 0xc0003b8f00, 0x2bd8080, 0xc0cc643650)
	/__w/cortex/cortex/pkg/ingester/client/cortex.pb.go:3316 +0x86 fp=0xc07925b3b0 sp=0xc07925b368 pc=0x13e4326
github.com/cortexproject/cortex/pkg/cortex.ThanosTracerUnaryInterceptor(0x2bd8080, 0xc0cc643620, 0x2488360, 0xc0cc643560, 0xc556e01dc0, 0xc556e01de0, 0xc315dfeff0, 0x2bd8080, 0xc0cc643620, 0xc315dfef10)
	/__w/cortex/cortex/pkg/cortex/tracing.go:14 +0xa3 fp=0xc07925b400 sp=0xc07925b3b0 pc=0x1ec7303
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2bd8080, 0xc0cc643620, 0x2488360, 0xc0cc643560, 0x2bd8080, 0xc0cc643620, 0x0, 0x0)
	/__w/cortex/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x63 fp=0xc07925b460 sp=0xc07925b400 pc=0xb333e3
github.com/weaveworks/common/middleware.ServerUserHeaderInterceptor(0x2bd8080, 0xc0cc6435f0, 0x2488360, 0xc0cc643560, 0xc556e01dc0, 0xc556e01e00, 0xc07925b510, 0x651c4d, 0x2393020, 0xc0cc6435f0)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/grpc_auth.go:38 +0x9e fp=0xc07925b4b0 sp=0xc07925b460 pc=0xc646fe
github.com/cortexproject/cortex/pkg/util/fakeauth.SetupAuthMiddleware.func1(0x2bd8080, 0xc0cc6435f0, 0x2488360, 0xc0cc643560, 0xc556e01dc0, 0xc556e01e00, 0x2504fe0, 0xc29331d0e0, 0x2bd8080, 0xc0cc6435f0)
	/__w/cortex/cortex/pkg/util/fakeauth/fake_auth.go:27 +0x116 fp=0xc07925b510 sp=0xc07925b4b0 pc=0x1eb4506
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2bd8080, 0xc0cc6435f0, 0x2488360, 0xc0cc643560, 0x2bd8080, 0xc0cc6435f0, 0x2c10460, 0xc29331d0e0)
	/__w/cortex/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x63 fp=0xc07925b570 sp=0xc07925b510 pc=0xb333e3
github.com/opentracing-contrib/go-grpc.OpenTracingServerInterceptor.func1(0x2bd8080, 0xc0cc6435f0, 0x2488360, 0xc0cc643560, 0xc556e01dc0, 0xc556e01e20, 0x0, 0x0, 0x0, 0x0)
	/__w/cortex/cortex/vendor/github.com/opentracing-contrib/go-grpc/server.go:57 +0x2d8 fp=0xc07925b7f0 sp=0xc07925b570 pc=0xb370b8
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2bd8080, 0xc0cc643530, 0x2488360, 0xc0cc643560, 0x87136c, 0xc00057b230, 0xe83b6b66d65ac2e9, 0xc556e01da0)
	/__w/cortex/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x63 fp=0xc07925b850 sp=0xc07925b7f0 pc=0xb333e3
github.com/weaveworks/common/middleware.UnaryServerInstrumentInterceptor.func1(0x2bd8080, 0xc0cc643530, 0x2488360, 0xc0cc643560, 0xc556e01dc0, 0xc556e01e40, 0x4db7f6, 0x6040bf29, 0x8cad8b9, 0x23414ebc41956)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/grpc_instrumentation.go:32 +0x9d fp=0xc07925b8e0 sp=0xc07925b850 pc=0xc67c4d
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2bd8080, 0xc0cc643530, 0x2488360, 0xc0cc643560, 0x1, 0x0, 0x203155, 0xc07925b9c8)
	/__w/cortex/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x63 fp=0xc07925b940 sp=0xc07925b8e0 pc=0xb333e3
github.com/weaveworks/common/middleware.GRPCServerLog.UnaryServerInterceptor(0x2c092e0, 0xc000209c30, 0x0, 0x2bd8080, 0xc0cc643530, 0x2488360, 0xc0cc643560, 0xc556e01dc0, 0xc556e01e60, 0xc4c4dc4f00, ...)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/grpc_logging.go:29 +0x98 fp=0xc07925b9f8 sp=0xc07925b940 pc=0xc64c58
github.com/weaveworks/common/middleware.GRPCServerLog.UnaryServerInterceptor-fm(0x2bd8080, 0xc0cc643530, 0x2488360, 0xc0cc643560, 0xc556e01dc0, 0xc556e01e60, 0xb334d9, 0x2326ae0, 0xc556e01e80, 0xc556e01dc0)
	/__w/cortex/cortex/vendor/github.com/weaveworks/common/middleware/grpc_logging.go:27 +0x8a fp=0xc07925ba70 sp=0xc07925b9f8 pc=0xc7306a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x2bd8080, 0xc0cc643530, 0x2488360, 0xc0cc643560, 0xc4bc1ef100, 0xc556e01d40, 0xc07925bb30, 0x40cfa8)
	/__w/cortex/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:25 +0x63 fp=0xc07925bad0 sp=0xc07925ba70 pc=0xb333e3
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x2bd8080, 0xc0cc643530, 0x2488360, 0xc0cc643560, 0xc556e01dc0, 0xc556e01de0, 0xc07925bba0, 0x651c4d, 0x2393020, 0xc0cc643530)
	/__w/cortex/cortex/vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go:34 +0xd5 fp=0xc07925bb40 sp=0xc07925bad0 pc=0xb335c5
github.com/cortexproject/cortex/pkg/ingester/client._Ingester_Query_Handler(0x2532300, 0xc00095a000, 0x2bd8080, 0xc0cc643530, 0xc460bc0480, 0xc00057b4d0, 0x2bd8080, 0xc0cc643530, 0xc4029b98c0, 0x34)
	/__w/cortex/cortex/pkg/ingester/client/cortex.pb.go:3318 +0x14b fp=0xc07925bbb0 sp=0xc07925bb40 pc=0x13c105b
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005531e0, 0x2c057e0, 0xc2f1d83080, 0xc4bc1ef100, 0xc0006bb1a0, 0x3f9aab8, 0x0, 0x0, 0x0)
	/__w/cortex/cortex/vendor/google.golang.org/grpc/server.go:1082 +0x50a fp=0xc07925be40 sp=0xc07925bbb0 pc=0xb0184a
google.golang.org/grpc.(*Server).handleStream(0xc0005531e0, 0x2c057e0, 0xc2f1d83080, 0xc4bc1ef100, 0x0)
	/__w/cortex/cortex/vendor/google.golang.org/grpc/server.go:1405 +0xccd fp=0xc07925bf68 sp=0xc07925be40 pc=0xb059dd
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0c2eb5f20, 0xc0005531e0, 0x2c057e0, 0xc2f1d83080, 0xc4bc1ef100)
	/__w/cortex/cortex/vendor/google.golang.org/grpc/server.go:746 +0xa1 fp=0xc07925bfb8 sp=0xc07925bf68 pc=0xb13b81
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc07925bfc0 sp=0xc07925bfb8 pc=0x467ca1
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/__w/cortex/cortex/vendor/google.golang.org/grpc/server.go:744 +0xa1
```

**Comment by pracucci** [comment] 2021-03-04 16:30
A theory is that `bstream.stream` is invalid because it was a slice from mmap-ed chunks which has been unmmap-ed. Following this theory, could be an issue related to head chunks mmapp-ing.

I'm thinking about something like this:
1. A query run `tsdb.Querier().Select()` in the ingester
2. The `Select()` returns a `SeriesSet` with a series referencing an mmap-ed chunk
3. TSDB unmmap the head chunk
4. The `SeriesSet` gets iterated in the ingester and when it's the time to read the chunk `[]byte` it's invalid because unmmap-ed

@codesome Thoughts?

**Comment by codesome** [comment] 2021-03-05 06:51
It's most likely what @pracucci mentioned, a TSDB bug. It was a similar case with blocks until we started keeping track of readers on blocks and wait for them to close before closing the block. Here with Head blocks its an interaction between Head compaction and queries.

We could keep track of queriers on TSDB and delay unmapping/deleting of m-mapped files based on time ranges of open queriers.

**Comment by codesome** [comment] 2021-03-05 06:57
Related issue https://github.com/prometheus/prometheus/issues/8318

**Comment by pracucci** [comment] 2021-03-16 11:43
Is this issue related to https://github.com/prometheus/prometheus/issues/8217 too?

**Comment by codesome** [comment] 2021-03-23 07:35
> Is this issue related to prometheus/prometheus#8217 too?

Yes I think so, not 100% sure since I don't know how things are connected there.

**Comment by pracucci** [comment] 2021-04-01 11:41
I should have reproduce the panic in this unit test:
https://github.com/prometheus/prometheus/pull/8681

**Closed** 2021-05-13 08:26 UTC
Labels: component/ingester, storage/blocks, type/bug
