### ISSUE TITLE
/prometheus/api/v1/rules auth middleware behaving incorrectly when auth disabled

### ISSUE THREAD

**Issue by sh0rez** [cortexproject/cortex#3300] opened 2020-10-08 15:14 UTC
**Describe the bug**

When running using `auth_enabled: false`, calling `/prometheus/api/v1/rules` without `X-Scope-OrgID` yields `500 Internal Server Error: no valid org id found`.

**To Reproduce**
1. Start Cortex (used `8d30827`):  
`go run go run ./cmd/cortex --config.file ./docs/configuration/single-process-config.yaml`
2. `GET` the endpoint (used [HTTPie](https://httpie.org/), but `curl` works as well:

```console
$ http localhost:9009/prometheus/api/v1/rules
HTTP/1.1 500 Internal Server Error
Content-Length: 89
Content-Type: text/plain; charset=utf-8
Date: Thu, 08 Oct 2020 15:06:10 GMT

{
    "data": null,
    "error": "no valid org id found",
    "errorType": "server_error",
    "status": "error"
}
```

**Expected behavior**

Instead of failing, I expected Cortex to silently assume `fake` as the org id, as specified by https://cortexmetrics.io/docs/production/auth/:

> To disable the multi-tenant functionality, you can pass the argument -auth.enabled=false to every Cortex component, which will set the OrgID to the string fake for every request.

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: go run? `go version go1.15.2 linux/amd64`

@pstibrany @owen-d

**Comment by sh0rez** [comment] 2020-10-08 15:15
Also note I'd be willing to give it a try to fix this myself, but I would need a bit of hints where to start looking

**Comment by gotjosh** [comment] 2020-10-08 17:01
I think this is a duplicate of #3260

**Comment by sh0rez** [comment] 2020-10-11 18:24
@gotjosh this one seems to be related to Alertmanager, while this is about the Prometheus compatible API itself. These might still be very well related.

**Closed** 2020-10-27 13:28 UTC
