### ISSUE TITLE
Add exporter for the overrides

### ISSUE THREAD

**Issue by codesome** [cortexproject/cortex#2957] opened 2020-07-30 15:06 UTC
The exporter would expose the overrides as Prometheus metrics which can be then displayed on a dashboard.

I already have it implemented. Would it make sense to have a separate repo under `cortexproject` for this exporter?

**Comment by pstibrany** [comment] 2020-07-30 15:09
Would it make sense to make it part of Cortex metrics?

**Comment by pracucci** [comment] 2020-07-30 16:07
Also related to https://github.com/cortexproject/cortex/issues/1433.

**Comment by pstibrany** [comment] 2020-07-30 17:16
> Would be a separate module in Cortex? (because we don't want it to be exposed by >1 pod)

Good point. Separate module would work in my opinion. Even if it is an extra pod, it would be tiny, and doing no work other than reloading config and publishing it via metrics. I think that's no different than having extra exporter. And in single-binary mode, it would just be part of "big" Cortex.

**Comment by pracucci** [comment] 2020-07-31 04:16
> And in single-binary mode, it would just be part of "big" Cortex.

If we run it in the `-target=all`, doesn't this introduce the high cardinality issue which prevented us from exporting these metrics directly from Cortex? Even in a small 10 nodes cluster, it will generate 10x series which I'm not sure it's what we want.

**Comment by pstibrany** [comment] 2020-07-31 06:12
> If we run it in the `-target=all`, doesn't this introduce the high cardinality issue which prevented us from exporting these metrics directly from Cortex? Even in a small 10 nodes cluster, it will generate 10x series which I'm not sure it's what we want.

You're right. I forgot that we encourage people to use multiple single-binary instances.

**Comment by weeco** [comment] 2020-07-31 08:01
What about an option where users can configure in what tenants' metrics the user is interested in? All tenants which aren't part of this list will be grouped together as "other_tenants" or so?

**Comment by simonswine** [comment] 2020-09-15 16:15
Another solution I could think of would be to expose the limits under a completely different path like `/metrics/limits` by default and then users can decide to scrape it through a config that would only scrape it once per cluster. (Like a kubernetes `role: service` discovery rule)

**Comment by pracucci** [comment] 2020-09-15 16:18
> Another solution I could think of would be to expose the limits under a completely different path like /metrics/limits by default and then users can decide to scrape it through a config that would only scrape it once per cluster.

I'm not sure it solves the problem. To conditionally expose these metrics we don't need a separate endpoint, but just a configuration option. However, if you enable it and these metrics are exposed by every single Cortex service then in a large cluster you will have very high cardinality metrics. To solve this, a solution would be creating a new target (which is one of the proposed solution).

**Comment by jtlisi** [comment] 2020-11-15 02:37
_still valid_

Any thoughts on closing this issue since an external exporter for this purpose exists here https://github.com/grafana/cortex-tools/pull/91?

**Comment by weeco** [comment] 2020-11-15 10:14
@jtlisi As described in https://github.com/cortexproject/cortex/issues/1433 as user I'd like to track how close the validation limits in order to see if a tenant is close to exceed them. Therefore I'd prefer to have the per tenant overrides along with the tenant usage exported as part of a cortex component.

**Comment by jtlisi** [comment] 2020-11-15 16:40
@weeco that makes sense. In that case I'm going to close this a duplicate of #1433

**Closed** 2020-11-15 16:40 UTC
