### ISSUE TITLE
Ruler does not currently support `/api/v1/rules` or `/api/v1/alerts`

### ISSUE THREAD

**Issue by jtlisi** [cortexproject/cortex#1720] opened 2019-10-07 19:50 UTC
Currently there isn't support in the cortex ruler match the prometheus rules or alerts endpoing. Ideally these endpoints can be supported in the future.

**Comment by bboreham** [comment] 2019-10-07 21:48
Duplicate of #378 ?

**Comment by khaines** [comment] 2019-10-07 23:10
They seem fairly similar, but after reading both of these I'm more inclined to close 378 and use this issue. The upstream issue 378 was related to was closed as it was superseded by the MR which added the api paths in the title.

**Closed** 2020-02-04 14:40 UTC
Labels: keepalive
