### ISSUE TITLE
cortex crash when exemplar label length exceed 128

### ISSUE THREAD

**Issue by wolf666666** [cortexproject/cortex#5232] opened 2023-03-27 10:20 UTC
The cortex querier service stopped some times as the exemplar label length exceed 128, from the source we know the limitation is 128, but from the log i can not find this is caused by which tenant and which exemplar.
I think there should be an validation parameter to discard this kind of exemplar, but i can not find it from the help doc(cortex --help), I also try to start it with debug level, this also have little help as there is little debug log in the source code, 
How should I validate the exemplar in the server side?

Here are the error messages:
00:07:38 linuxuser cortex-1.14.1[543559]: panic: exemplar labels have 734 runes, exceeding the limit of 128 [recovered]
00:07:38 linuxuser cortex-1.14.1[543559]:         panic: exemplar labels have 734 runes, exceeding the limit of 128

**Comment by wolf666666** [comment] 2023-03-27 14:40
After investigation, this should be cause by Tenant federation, when federation, the organization name is the combination all of the tenant name, the exemplar just have to labels: org and traceid, but the org is too long when it have a lot tenant.
I don't know how to resolve it.

**Comment by yeya24** [comment] 2023-11-09 16:59
Let's move this to release 1.17. Unfortunately we couldn't make it for 1.16

**Comment by yeya24** [comment] 2023-11-09 23:11
@wolf666666 One question, where is the bad exemplar coming from? They are ingested via remote write or they are part of the Cortex metric and we instrument with exemplars.

To me it sounds the latter as the error is coming from `client_golang`.

> After investigation, this should be cause by Tenant federation, when federation, the organization name is the combination all of the tenant name, the exemplar just have to labels: org and traceid, but the org is too long when it have a lot tenant.

Also trying to understand where is the instrumentation comes from... Is it from `weaveworks/common`? It feels quite unnecessary to me to attach org ID as exemplar label... Trace ID should be good enough. Maybe we can change it

**Comment by yeya24** [comment] 2023-11-19 04:37
Looking at Cortex code, I couldn't find out where we instrument exemplar with org ID label. I can see we only add `traceID` label in exemplar. Additional labels in exemplar is possible via https://github.com/prometheus/client_golang/blob/main/prometheus/promhttp/option.go#L72C6-L72C29, but I don't see it is used in Cortex.
I will close this issue so far due to lack of ways to reproduce. If you find out the code path or ways to reproduce it, feel free to let me know and reopen the issue.

Thanks

**Closed** 2023-11-19 04:45 UTC
Labels: type/bug, component/querier
