### ISSUE TITLE
There may be duplicate data points when merging series from ingester and store-gateway

### ISSUE THREAD

**Issue by wangzhao765** [cortexproject/cortex#3952] opened 2021-03-15 02:58 UTC
This bug is caused by prometheus client and is reported in issue https://github.com/prometheus/prometheus/issues/8558 .
I think we should upgrade the prometheus client to fix this issue.

**Comment by pstibrany** [comment] 2021-03-15 07:26
Thank you for heads-up!

**Comment by alvinlin123** [comment] 2021-03-17 22:46
This might be the root cause of https://github.com/cortexproject/cortex/issues/3920.

**Comment by bboreham** [comment] 2021-03-19 10:59
This should be fixed by #3934, right?

**Comment by pracucci** [comment] 2021-03-22 17:16
> This might be the root cause of #3920.

The issue you're describing in #3920 looks to be caused by the query-frontend, so I think this issue is unrelated.

> This should be fixed by #3934, right?

Yes.

**Closed by pracucci** 2021-03-22 17:16 UTC
