### ISSUE TITLE
ingester_v2 reporting quite a bit of "failed to delete idle TSDB" error

### ISSUE THREAD

**Issue by alvinlin123** [cortexproject/cortex#3620] opened 2020-12-19 20:33 UTC
**Describe the bug**
We are seeing error message like 

```
level=error ts=2020-12-15T21:33:44.395830698Z caller=ingester_v2.go:1623 msg="failed to delete idle TSDB" user=some-user-id err="unlinkat /data/tsdb/some-user-id: directory not empty"
```
We are using [this commit](https://github.com/cortexproject/cortex/tree/af9e20c54ee97f409008f3e86541c5dfa5038e22)

**To Reproduce**
I am not sure

**Expected behavior**

**Environment:**
 - Infrastructure: EKS 
 - Deployment tool: Helm

**Storage Engine**
- [ X ] Blocks
- [ ] Chunks

**Additional Context**
The error happens during a call to `os.RemoveAll()` call, research shows that `RemoveAll()` might return "directory not empty" error if file are created under the directory while the removal process is on going. So I am wondering if there is any background process in ingester that maybe interfering with the local TSDB deletion process?

**Comment by pstibrany** [comment] 2020-12-19 20:35
Would it be possible to check those non-empty directories and see what files are there?

**Comment by alvinlin123** [comment] 2020-12-19 20:39
I am on the same thought trail @pstibrany  :-) 

I just looked the directory has a single 

`thanos.shipper.json` file hmmm, shipper running concurrently?

**Comment by pstibrany** [comment] 2020-12-19 21:14
> Shipper running concurrently?

Thanks, that may actually be the case.

**Comment by alvinlin123** [comment] 2020-12-20 06:55
Should there be some kind of lock or retry then? If using lock, I wonder if it will affect overall performance if the `ship_interval` is configure at a low number.

**Comment by pstibrany** [comment] 2020-12-20 08:12
> Should there be some kind of lock or retry then? If using lock, I wonder if it will affect overall performance if the `ship_interval` is configure at a low number.

I was thinking of something simpler:
- add a wait group per TSDB, that would be increased when shipping starts, and “done” when shipping (call to Sync) is finished
- when closing TSDB with shipper, first stop shipping and then “wait” for sync group to make sure that shipper is really stopped. Only delete directory after this step.

This doesn’t affect performance of shipping. The only tricky part is how to write a unit test for it. (Likely with mocked shipper, whose Sync takes a long time, and we verify that dir isn’t deleted until Sync finishes).

There may be a better way to solve this, but I think this should work. Would you like to send a PR?

**Comment by pstibrany** [comment] 2020-12-20 08:23
> * when closing TSDB with shipper, first stop shipping (there is shipper context already) and then “wait” for sync group to make sure that shipper is really stopped. Only delete directory after this step.

“there is shipper context already” – I misremembered this. There isn’t.

Since shipping only works for users which are in `i.TSDBState.dbs`, we can do this check *after* removing user from this map. There will still be a race... as `getTSDBUsers` returns a copy of the map (used by `shipBlocks`) so I’d suggest modifying `shipBlocks` to check for `closing` and `closed` state of TSDB, and avoid shipping if one of these is set.

**Comment by pracucci** [comment] 2020-12-23 11:06
> so I’d suggest modifying shipBlocks to check for closing and closed state of TSDB, and avoid shipping if one of these is set

This wouldn't solve the race condition anyway. `shipBlocks()` may pass that check and then the closing of the idle TSDB may happen while shipping is still on-going.

**Comment by pracucci** [comment] 2020-12-23 11:20
> add a wait group per TSDB, that would be increased when shipping starts, and “done” when shipping (call to Sync) is finished

I don't think this is viable too, because of a property of `sync.WaitGroup` which I recently learned (and I believe there's some already existing misuse):

> Note that calls with a positive delta that occur when the counter is zero must happen before a Wait. Calls with a negative delta, or calls with a positive delta that start when the counter is greater than zero, may happen at any time. Typically this means the calls to Add should execute before the statement creating the goroutine or other event to be waited for. If a WaitGroup is reused to wait for several independent sets of events, new Add calls must happen after all previous Wait calls have returned. See the WaitGroup example.

**Comment by pstibrany** [comment] 2020-12-23 11:40
> I don't think this is viable too, because of a property of `sync.WaitGroup` which I recently learned (and I believe there's some already existing misuse):

I don’t see how that’s a misuse, or how that contradicts suggested usage.

**Comment by pracucci** [comment] 2020-12-23 11:42
> > I don't think this is viable too, because of a property of `sync.WaitGroup` which I recently learned (and I believe there's some already existing misuse):
> 
> I don’t see how that’s a misuse, or how that contradicts suggested usage.

When you call `Wait()` you need to have the guarantee that the WaitGroup counter is > 0, but you don't have it, unless you add an extra protection around it.

I'm currently experimenting the idea to add another `userTSDB` state `activeShipping`. Being able to use the `casState()` is quite handy and code changes would be minimal.

**Comment by pstibrany** [comment] 2020-12-23 11:44
> When you call `Wait()` you need to have the guarantee that the WaitGroup counter is > 0, but you don't have it, unless you add an extra protection around it.

This is not true. `Wait()` can be called if there was no `Add` before. 

What the comment you quoted says is that you cannot call `Add` while there is another **blocked** `Wait` in progress. But that is not our scenario.

**Comment by pstibrany** [comment] 2020-12-23 11:50
In different words, `WaitGroup` remembers two things: “value” (modified via `Add/Done`) and number of “waiters”. If “value” is 0, `Wait()` doesn’t increase “waiters” but returns immediately. If “waiters” > 0, “value” cannot be increased (this is what comment is about).

**Comment by pstibrany** [comment] 2020-12-23 11:52
Back to our problem... since there is only single shipper per TSDB which can increase WaitGroup, I think it’s a viable solution.

**Comment by pracucci** [comment] 2020-12-23 12:14
> I'm currently experimenting the idea to add another userTSDB state activeShipping. Being able to use the casState() is quite handy and code changes would be minimal.

I was already working on it, so I've completed that attempt https://github.com/cortexproject/cortex/pull/3632.

_Now going to investigate the `sync.WaitGroup`._

**Comment by pracucci** [comment] 2020-12-23 13:36
> In different words, WaitGroup remembers two things: “value” (modified via Add/Done) and number of “waiters”. If “value” is 0, Wait() doesn’t increase “waiters” but returns immediately. If “waiters” > 0, “value” cannot be increased (this is what comment is about).

To my understanding of the doc, if "waiters" > 0, "value" cannot be increased only in the case the current value is 0. The doc says:

> Calls with a negative delta, or calls with a positive delta that start when the counter is greater than zero, may happen at any time.

My idea was to have `shipBlocks()` doing `wg.Add(1)` and `defer wg.Done()`, and `closeAndDeleteUserTSDBIfIdle()` calling `wg.Wait()` after switching to `closing` state. To my understanding, this leads to a race condition in `WaitGroup`, because it's exactly the case not supported (see also the race condition reproduced here: https://gist.github.com/pracucci/09cc52e0cd35c8b96cc8cac79bda78fd).

To solve it, we would have to wrap `wg.Add(1)` with the `userTSDB.stateMtx` lock, checking the current state before doing it. I've the feeling this approach is more complex and probably more error prone, so I've propose a solution based on a new state.

**Comment by pstibrany** [comment] 2020-12-23 15:00
> To my understanding of the doc, if "waiters" > 0, "value" cannot be increased only in the case the current value is 0.

Right, that's also what I wrote.

> My idea was to have `shipBlocks()` doing `wg.Add(1)` and `defer wg.Done()`, and `closeAndDeleteUserTSDBIfIdle()` calling `wg.Wait()` after switching to `closing` state. To my understanding, this leads to a race condition in `WaitGroup`, because it's exactly the case not supported (see also the race condition reproduced here: https://gist.github.com/pracucci/09cc52e0cd35c8b96cc8cac79bda78fd).
> 
> To solve it, we would have to wrap `wg.Add(1)` with the `userTSDB.stateMtx` lock, checking the current state before doing it. I've the feeling this approach is more complex and probably more error prone, so I've propose a solution based on a new state.

Right. I don't think it's "more complex"... this is also we do in `acquireAppendLock`.

Your linked test case calls `Wait` repeatedly without any additional synchronization. That is wrong, since it doesn't give `Wait` to actually finish before calling `Add` again. In our scenario, there would only be single call to `Wait`, but race is still there without the check on state with lock held that you propose. I missed that in my original proposal.

**Closed** 2021-01-04 13:47 UTC
Labels: storage/blocks
