### ISSUE TITLE
Query error after upgrade to 1.0.0

### ISSUE THREAD

**Issue by AndreZiviani** [cortexproject/cortex#2396] opened 2020-04-02 17:20 UTC
Hi, I was using Cortex 0.7.0 with TSDB engine storing in AWS S3 Bucket without problems.

After upgrading to version 1.0.0 I got the error `cannot iterate chunk for series` when querying for values older than 1h, when I refresh the dashboard the error moves to another panel:
![image](https://user-images.githubusercontent.com/7469258/78278581-9fc7d980-74ec-11ea-8747-a12c4d152283.png)
![image](https://user-images.githubusercontent.com/7469258/78278616-aeae8c00-74ec-11ea-96f1-4467fb12fe06.png)

This is my current config (running in "single process" mode):
```
auth_enabled: true

server:
  log_level: info
  http_listen_port: 9009

  # Configure the server to allow messages up to 100MB.
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000

distributor:
  shard_by_all_labels: true
  pool:
    health_check_ingesters: true
  ring:
    kvstore:
      store: consul

ingester_client:
  grpc_client_config:
    # Configure the client to allow messages up to 100MB.
    max_recv_msg_size: 104857600
    max_send_msg_size: 104857600
    use_gzip_compression: true

ingester:

  lifecycler:
    # The address to advertise for this ingester.  Will be autodiscovered by
    # looking up address on eth0 or en0; can be specified if this fails.
    address: 0.0.0.0

    # Use an in memory ring store, so we don't need to launch a Consul.
    ring:
      kvstore:
        store: consul
      replication_factor: 1
    num_tokens: 512
  
storage:
  engine: tsdb

tsdb:
  backend: s3
  dir: "/cortex/tsdb"
  bucket_store:
    sync_dir: "/cortex/tsdb-sync"
    sync_interval: 1h # default: 5m
    index_cache:
      backend: memcached
      memcached:
        addresses:[REDACTED]:11211
      postings_compression_enabled: true
  s3:
    bucket_name: [REDACTED]
    endpoint: s3.dualstack.us-east-1.amazonaws.com

limits:
  ingestion_rate: 250000

compactor:
  data_dir: "/cortex/compactor"

query_range:
  split_queries_by_interval: 24h

frontend:
  compress_responses: true
  log_queries_longer_than: 1s
```

**Comment by AndreZiviani** [comment] 2020-04-02 17:27
More info that could be usefull
![image](https://user-images.githubusercontent.com/7469258/78279430-dfdb8c00-74ed-11ea-953a-029f8efd4220.png)
![image](https://user-images.githubusercontent.com/7469258/78279512-039ed200-74ee-11ea-82eb-bb5a69c54ced.png)

**Comment by kubicgruenfeld** [comment] 2020-04-02 17:51
I am not 100 % sure, but maybe we have the same issue, we are not using AWS S3 but a "compatible reimplementation of S3" from Quobyte.

The queriers are logging these for failed queries:

```
level=error ts=2020-04-02T17:12:28.435445802Z caller=worker.go:167 msg="error processing requests" err="rpc error: code = Canceled desc = context canceled"
```

I did some tcpdumping and saw some GET Requests with Range Headers failing with HTTP Statuscode 416.

```
2502	34.422156	151.252.46.52	172.25.16.15	HTTP/XML	541	HTTP/1.1 416 Range Not Satisfiable 
```

Since, we had at first issues because of our S3-compatible-implementation was rate-limiting, maybe there are still just too many requests. I also opened https://github.com/thanos-io/thanos/pull/2343 in the hope it would address the issue with too many connections (was just merged). I wonder if AWS does rate-limiting as well and maybe this is still the main issue here.

I also had a long conversation in your slack channel over this topic here: https://cloud-native.slack.com/archives/CCYDASBLP/p1585211354038800

I can provide more information if needed and thanks for looking into this.

**Comment by pracucci** [comment] 2020-04-03 08:00
Thanks for reporting it. I can reproduce it as well and I confirm it's a bug (even if I haven't found the root cause). I'm working on it as top priority.

As a side note, the GET error rate may be unrelated and actually be a false positive (not an error) caused by a bug in the metrics tracking we're trying to fix [here](https://github.com/thanos-io/thanos/pull/2365) and/or [here](https://github.com/thanos-io/thanos/pull/2369). I'm suspecting it because chunks are fetched using a `get_range` (for which I can't see any error).

**Comment by pracucci** [comment] 2020-04-03 08:26
The issue looks to be introduced by my change in the PR #2324 and is caused by the fact that chunks slices are reused in Thanos and we just keep references in Cortex instead of copying them. Sorry for that!

_I'm working on a fix._

**Closed** 2020-04-03 09:45 UTC

**Comment by AndreZiviani** [comment] 2020-04-03 12:28
Thanks for the quick fix! It worked!
