### ISSUE TITLE
Ingesters continuously log the warning message method=/cortex.Ingester/QueryStream err="context canceled" msg="gRPC\n"

### ISSUE THREAD

**Issue by nrjpoddar** [cortexproject/cortex#1279] opened 2019-03-13 20:45 UTC
We are running cortex version `master-4d5a8a70` and see that all the ingesters are continuously logging this warning message:

```bash
level=warn ts=2019-03-13T20:38:59.792970914Z caller=gokit.go:46 method=/cortex.Ingester/QueryStream duration=61.047µs err="rpc error: code = Canceled desc = context canceled" msg="gRPC\n"
``` 

This log doesn't really contain all the information needed to debug the issue. These are our options for the ingester Pod if it's related to configuration:

```yaml
        - -ingester.join-after=30s
        - -ingester.claim-on-rollout=true
        - -ingester.search-pending-for=5m
        - -consul.hostname=<>
        - -dynamodb.original-table-name=<>
        - -dynamodb.url=dynamodb://$(AWS_DEFAULT_REGION)
        - -s3.url=<>
        - -dynamodb.chunk-table.prefix=cortex_chunks_
        - -dynamodb.chunk-table.tag=cortex=chunks
        - -dynamodb.chunk-table.from=<>
        - -dynamodb.chunk-table.period=168h
        - -dynamodb.periodic-table.prefix=cortex_weekly_
        - -dynamodb.periodic-table.tag=cortex=periodic-table
        - -dynamodb.periodic-table.from=<>
        - -dynamodb.periodic-table.period=168h
        - -dynamodb.v6-schema-from=<>
        - -dynamodb.use-periodic-tables
        - -memcached.hostname=<>
        - -memcached.timeout=100ms
        - -memcached.service=memcache
        - -memcached.timeout=500ms
        - -store.index-cache-write.memcached.hostname=<>
        - -store.index-cache-write.memcached.service=memcache
        - -store.index-cache-write.memcached.timeout=500ms
        - -store.index-cache-read.memcached.hostname=<>
        - -store.index-cache-read.memcached.service=memcache
        - -store.index-cache-read.memcached.timeout=500ms
```

**Comment by bboreham** [comment] 2019-03-13 22:56
Thanks for filing this. Mine are the same. 

Note that the querier will always send requests to N ingsay

**Comment by nrjpoddar** [comment] 2019-03-13 23:00
That makes sense, I will try and submit a PR to address it.

**Comment by nrjpoddar** [comment] 2019-03-14 00:53
Looks like the logging is handled at the common layer via interceptors on the gRPC server: https://github.com/cortexproject/cortex/blob/master/vendor/github.com/weaveworks/common/middleware/grpc_logging.go#L42

Should we add a custom logging gRPC interceptor for the ingester server?
We can also filter based on methods passed in the interceptor during initialization but that seems like a maintenance nightmare.

**Comment by csmarchbanks** [comment] 2019-03-14 02:51
You can also try setting `-distributor.extra-query-delay` to about the 95th percentile response time of the latency to your ingester. This will cause the queries needed for more than a quorum will wait to be sent and you will only have a context cancelled error if talking to an ingester is actually slow.

The 95th percentile recommendation comes from http://www.cs.duke.edu/courses/cps296.4/fall13/838-CloudPapers/dean_longtail.pdf You can set it to whatever you want though.

**Comment by bboreham** [comment] 2019-03-14 09:34
> Should we add a custom logging gRPC interceptor for the ingester server?

As opposed to changing `weaveworks/common` for every server?  I'm for that.
"Context cancelled" is always expected, in my view.  User can hit `x` on their browser, etc.

**Comment by nrjpoddar** [comment] 2019-03-17 18:14
@csmarchbanks I will try that option and see if it works as expected.

@bboreham I don't know if `weaveworks/common` is used in other places where you might want to log "Context cancelled".  I am thinking of cases where an API is exposed for server-to-server communication which is invoked asynchronously and not in the context of an end user request. Ruler is a good example of this.  Changing `weaveworks/common` to always ignore "Context cancelled" error messages might be too broad.

**Comment by bboreham** [comment] 2019-03-17 18:55
Context cancelled is not an error, it is expected in any client-server interaction.

**Comment by nrjpoddar** [comment] 2019-03-19 16:30
@bboreham I filed this PR: https://github.com/weaveworks/common/pull/151 for addressing this issue. Once you're review/approve it, I will submit a PR to cortex to update dependencies.

**Comment by bboreham** [comment] 2019-04-03 12:58
This is probably a duplicate of #465

**Closed** 2019-04-24 09:46 UTC
