### ISSUE TITLE
"error updating memcache servers"  in AWS

### ISSUE THREAD

**Issue by pablokbs** [cortexproject/cortex#1501] opened 2019-07-10 13:48 UTC
I'm running cortex in AWS and using memcached in elasticache, seems like the service is trying to do a `SRV` request to the hostname for memcached and failing to get a response (as seems like AWS doesn't provide that record)

`level=warn ts=2019-07-10T13:43:16.739687937Z caller=memcached_client.go:92 msg="error updating memcache servers" err="lookup _memcached._tcp.test-cortex.xxxxx.cfg.use1.cache.amazonaws.com on 10.80.25.218:53: no such host"`

I ran dig on a pod and didn't get any response from aws:

```
# dig srv _memcached._tcp.test-cortex.xxxxx.cfg.use1.cache.amazonaws.com  +short
# 
```

**Comment by codyja** [comment] 2019-08-04 16:39
I'm hitting this same issue in AWS. Running memcached in a container under ECS with service discovery. 
```
level=error ts=2019-08-04T16:36:56.483285795Z caller=memcached_client.go:69 msg="error setting memcache servers to host" host=memcached.cortex-development err="lookup _memcached._tcp.memcached.cortex-development on 10.0.0.50:53: no such host"
```

**Comment by gouthamve** [comment] 2019-09-18 14:36
Dupe of #1505

**Closed by gouthamve** 2019-09-18 14:36 UTC
